### ISSUE TITLE
Container crashes

### ISSUE THREAD

**Issue by max-rocket-internet** [caicloud/event_exporter#20]
After running for a while, I see this printed over and over:

```
W0904 15:26:14.287525       1 reflector.go:334] github.com/caicloud/event_exporter/store.go:111: watch of *api.Event ended with: The resourceVersion for the provided watch is too old.
W0904 15:36:14.476497       1 reflector.go:334] github.com/caicloud/event_exporter/store.go:111: watch of *api.Event ended with: The resourceVersion for the provided watch is too old.
```

Then:

```
fatal error: concurrent map writes

goroutine 31137 [running]:
runtime.throw(0x1478e97, 0x15)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc42054ebe0 sp=0xc42054ebc0
runtime.mapassign1(0x12fd240, 0xc42028b890, 0xc42054ed58, 0xc42054ed68)
	/usr/local/go/src/runtime/hashmap.go:458 +0x8ef fp=0xc42054ecc8 sp=0xc42054ebe0
github.com/caicloud/event_exporter/vendor/k8s.io/kubernetes/pkg/client/cache.(*DeltaFIFO).queueActionLocked(0xc4200904d0, 0x14657ad, 0x4, 0x143ee20, 0xc420120800, 0x1, 0x0)
	/home/vagrant/gocode/src/github.com/caicloud/event_exporter/vendor/k8s.io/kubernetes/pkg/client/cache/delta_fifo.go:314 +0x249 fp=0xc42054edb0 sp=0xc42054ecc8
github.com/caicloud/event_exporter/vendor/k8s.io/kubernetes/pkg/client/cache.(*DeltaFIFO).Resync(0xc4200904d0, 0x0, 0x0)
	/home/vagrant/gocode/src/github.com/caicloud/event_exporter/vendor/k8s.io/kubernetes/pkg/client/cache/delta_fifo.go:498 +0x179 fp=0xc42054ee88 sp=0xc42054edb0
github.com/caicloud/event_exporter/vendor/k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch.func1(0xc42032e0f0, 0xc420516ae0, 0xc4202ad860, 0xc420517740, 0xc42032e0f8)
	/home/vagrant/gocode/src/github.com/caicloud/event_exporter/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:289 +0x1b5 fp=0xc42054ef88 sp=0xc42054ee88
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42054ef90 sp=0xc42054ef88
created by github.com/caicloud/event_exporter/vendor/k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch
	/home/vagrant/gocode/src/github.com/caicloud/event_exporter/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:296 +0x4c0

goroutine 1 [IO wait, 2756 minutes]:
net.runtime_pollWait(0x7f396b5cf870, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420354990, 0x72, 0xc4204d3ab8, 0xc42001c0b0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420354990, 0x1e48ba0, 0xc42001c0b0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc420354930, 0x0, 0x1e46e60, 0xc4202835c0)
	/usr/local/go/src/net/fd_unix.go:419 +0x238
net.(*TCPListener).accept(0xc4201b0058, 0x29e8d60800, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:132 +0x2e
net.(*TCPListener).AcceptTCP(0xc4201b0058, 0xc4204d3be0, 0xc4204d3be8, 0xc4204d3bd8)
	/usr/local/go/src/net/tcpsock.go:209 +0x49
net/http.tcpKeepAliveListener.Accept(0xc4201b0058, 0x150cab0, 0xc420368b00, 0x1e53360, 0xc4201afb00)
	/usr/local/go/src/net/http/server.go:2608 +0x2f
net/http.(*Server).Serve(0xc420368080, 0x1e52c20, 0xc4201b0058, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2273 +0x1ce
net/http.(*Server).ListenAndServe(0xc420368080, 0xc420368080, 0x2)
	/usr/local/go/src/net/http/server.go:2219 +0xb4
net/http.ListenAndServe(0x1465f8d, 0x5, 0x0, 0x0, 0xc4203e64b0, 0x0)
	/usr/local/go/src/net/http/server.go:2351 +0xa0
main.main()
	/home/vagrant/gocode/src/github.com/caicloud/event_exporter/main.go:107 +0x59a

goroutine 17 [syscall, 2756 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 7 [chan receive]:
github.com/caicloud/event_exporter/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x1e6ecc0)
	/home/vagrant/gocode/src/github.com/caicloud/event_exporter/vendor/github.com/golang/glog/glog.go:879 +0x7a
created by github.com/caicloud/event_exporter/vendor/github.com/golang/glog.init.1
	/home/vagrant/gocode/src/github.com/caicloud/event_exporter/vendor/github.com/golang/glog/glog.go:410 +0x21d

goroutine 23 [syscall, 2756 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 24 [chan receive, 2756 minutes]:
main.(*EventStore).Run(0xc4201b5220)
	/home/vagrant/gocode/src/github.com/caicloud/event_exporter/store.go:112 +0xf5
created by main.main
	/home/vagrant/gocode/src/github.com/caicloud/event_exporter/main.go:95 +0x1e4

goroutine 11122 [select, 3 minutes]:
net/http.(*persistConn).readLoop(0xc4204ee500)
	/usr/local/go/src/net/http/transport.go:1541 +0x9c9
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1062 +0x4e9
```

A bit more of that and then this repeating:

```
goroutine 15512 [select, 1 minutes]:
github.com/caicloud/event_exporter/vendor/k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch.func1(0xc4201b00f8, 0xc420516ae0, 0xc4202ad860, 0xc4204818c0, 0xc4201b0100)
	/home/vagrant/gocode/src/github.com/caicloud/event_exporter/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:283 +0x303
created by github.com/caicloud/event_exporter/vendor/k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch
	/home/vagrant/gocode/src/github.com/caicloud/event_exporter/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:296 +0x4c0
```

Then container container is killed by k8s.

Here's the container information from k8s:

```
Containers:
  app:
    Container ID:  docker://87c603584b7d193716ecb79f70a10a8ed49e4050fc1e89412322e09a233473a9
    Image:         cargo.caicloud.io/sysinfra/event-exporter:latest
    Image ID:      docker-pullable://cargo.caicloud.io/sysinfra/event-exporter@sha256:826f54f71c3802f59164a108b87a7a5b002efccbd80e0d13c3da94140baf5c3a
    Port:          9102/TCP
    Host Port:     0/TCP
    Args:
      --logtostderr
    State:          Running
      Started:      Wed, 04 Sep 2019 14:03:32 +0200
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Mon, 02 Sep 2019 16:07:08 +0200
      Finished:     Wed, 04 Sep 2019 14:03:31 +0200
    Ready:          True
    Restart Count:  1
    Limits:
      cpu:     200m
      memory:  128Mi
    Requests:
      cpu:        100m
      memory:     128Mi
    Environment:  <none>
```

/kind bug

**What happened**:

Container crashes

**What you expected to happen**:

Container not to crash.

**How to reproduce it (as minimally and precisely as possible)**:

Just run it for 1-5 days.

**Comment by supereagle** [comment]
What's your Kubernetes version? The `event-exporter` you used is too old, maybe does not match your Kubernetes version.

**Comment by max-rocket-internet** [comment]
Hi @supereagle 
We running k8s version `1.12.10`

> The event-exporter you used is too old, maybe does not match your Kubernetes version.

OK but there's no docker tags listed anywhere. I checked main readme and [here](https://cargo.caicloud.io/). So I just used `cargo.caicloud.io/sysinfra/event-exporter` as per the main readme so I guess that should be the latest?

**Comment by supereagle** [comment]
@max-rocket-internet  You can have a try on `supereagle/event-exporter:v0.2.0-beta`, it has been adjust for k8s 1.12 ~ 1.14. If it is ok, I will create a new release.

**Comment by max-rocket-internet** [comment]
OK thanks, I'll test it and report back in a day or so 🙂

**Comment by max-rocket-internet** [comment]
@supereagle thanks! No crashes for 24 hours so I think this docker image is good.

Could you create a release tag in this repo and a docker image tag to match?

**Comment by supereagle** [comment]
@max-rocket-internet Thanks for your report. 

I have created the latest release: https://github.com/caicloud/event_exporter/releases/tag/v0.2.0

**Comment by max-rocket-internet** [comment]
Thanks!

What's the docker tag for this release? I tried `cargo.caicloud.io/sysinfra/event-exporter:v0.2.0` and `cargo.caicloud.io/sysinfra/event-exporter:0.2.0` but no luck?

**Comment by supereagle** [comment]
It is `caicloud/event-exporter:v0.2.0`, which has been mentioned in release note.

![image](https://user-images.githubusercontent.com/3390333/64468750-e1f98a00-d15a-11e9-8519-06b9ef053431.png)

**Comment by max-rocket-internet** [comment]
OK thanks @supereagle!

It might be nice to update the main README with the new docker image and also push a `caicloud/event-exporter:latest` 🙂

**Comment by supereagle** [comment]
It is not recommended to use the `latest` tag, as it is hard to track its version. I have created the PR #22 to update the readme, please take a look.
